### ISSUE TITLE
Fail to run `azd pipeline config` command 

### ISSUE THREAD

**Issue by faynef** [Azure-Samples/contoso-creative-writer#113]
**Describe the issue:**
When executing `azd pipeline config`, the error is as follows:
- Validate AZD template:
![image](https://github.com/user-attachments/assets/bba1392a-88cb-453e-a30e-53af291d2db7)
- Azd provision and deploy:
![image](https://github.com/user-attachments/assets/9d31e877-b0b2-4969-b73a-712ba11a6baa)

- Evaluate:
![image](https://github.com/user-attachments/assets/1d661f87-13a5-4d90-a978-3e054a4b92f9)

**Repro Steps:**

1. Run `azd auth login`.
2. Run `az login`.
3. Configure terraform.
4. Run `azd pipeline config`.
5. Add a role assignment of this service principal on tfstate storage account.

**Environment:**

- Azd version: azd version 1.9.5 (commit cd2b7af9995d358aab33c782614f801ac1997dde)
- OS: Codespaces, Dev Containers and Windows.

**Expected behavior:**
Run`azd pipeline config` successfully.

@jongio and @marlenezw for notification.

**Comment by marlenezw** [comment]
Issue resolved

**Comment by faynef** [comment]
The old problem was fixed, but some new problems emerged: all workflows could not run automatically and errors occurred, as shown below:

- Deploy:

![image](https://github.com/user-attachments/assets/05cb3815-9ad5-4bf8-81f4-a18c5c0c5217)

- Evaluate:

![image](https://github.com/user-attachments/assets/47e8ec7b-d9cd-4dbb-b159-79fd4ef06b75)

- Validate AZD template:

![image](https://github.com/user-attachments/assets/53cae8a9-eb63-49de-9520-daff55f39a70)
