### ISSUE TITLE
Fail to run `azd up` command 

### ISSUE THREAD

**Issue by faynef** [Azure-Samples/contoso-creative-writer#114]
**Describe the issue:**
When executing `azd up`, the error is as follows:
![image](https://github.com/user-attachments/assets/168c0ff5-9cb9-483e-a94e-34b67b8e42ec)
**Repro Steps:**

1. Run `azd auth login`.
2. Run `azd up`.

**Environment:**
- Azd version: azd version 1.9.5 (commit cd2b7af9995d358aab33c782614f801ac1997dde)
- OS: Codespaces

**Expected behavior:**
Run`azd up` successfully.

@jongio and @marlenezw for notification.

**Comment by marlenezw** [comment]
Issue resolved, no longer using TF on main
