### ISSUE TITLE
Deployment fail using Code space

### ISSUE THREAD

**Issue by Mvenkateswaramma** [Azure-Samples/contoso-creative-writer#165]
Hello,
Using code space deployment is fail 
ERROR: error executing step command 'provision': deployment failed: error deploying infrastructure: deploying to subscription:

Deployment Error Details:
InvalidTemplateDeployment: The template deployment 'cognitiveServices' is not valid according to the validation procedure. The tracking id is '12e51e55-3dee-4037-9458-9a7f85c416cc'. See inner errors for details.
InvalidResourceProperties: The specified SKU 'Standard' for model 'gpt-35-turbo 1106' is not supported in this region 'eastus2'.
![code space](https://github.com/user-attachments/assets/1de2ecf4-8bc6-4527-9598-7799ee3799cd)

**Comment by marlenezw** [comment]
Hi @Mvenkateswaramma could you try deploying again but with `canadaeast`? Thanks
