### ISSUE TITLE
Web app stalled

### ISSUE THREAD

**Issue by vlad-tsoy** [Azure-Samples/contoso-creative-writer#204]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Deployed the example in a container, executed 'npm run dev', opened the local URL: http://localhost:5173/ and the app is continuously loading

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> macOS Sequoia

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by marlenezw** [comment]
I tested and this should work now. Thanks
